In [1]:
from sklearn.datasets import make_classification

In [2]:
import torch

In [ ]:
# step1 Create a synthetic classification 

In [3]:
X,y = make_classification(
    n_samples = 10,     # no. of samples
    n_features = 2 ,    
    n_informative = 2 ,   # no. of informative features
    n_redundant = 0,      # no. of redundant feaatures
    n_classes = 2,        # no. of classes
    random_state = 42     # for reproducibility
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
X.shape

(10, 2)

In [8]:
y.shape

(10,)

In [ ]:
X = torch.tensor(X , dtype=torch.float32)


/tmp/ipython-input-1484248944.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X , dtype=torch.float32)


In [11]:
y = torch.tensor(y , dtype = torch.long)

/tmp/ipython-input-3969967997.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y = torch.tensor(y , dtype = torch.long)


In [12]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [13]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [16]:
from torch.utils.data import Dataset , DataLoader

In [17]:
class CustomDataset(Dataset):
    def __init__(self , features , labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self , index):
        return self.features[index] , self.labels[index]

In [18]:
dataset = CustomDataset(X , y)

In [21]:
len(dataset)

10

In [22]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [23]:
dataloader = DataLoader(dataset , batch_size = 2 , shuffle=True)

In [24]:
for batch_features , batch_loaders in dataloader:
    print(batch_features)
    print(batch_loaders)
    print('-'*50)

tensor([[-0.5872, -1.9717],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[1.7774, 1.5116],
        [1.8997, 0.8344]])
tensor([1, 1])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [ 1.7273, -1.1858]])
tensor([1, 1])
--------------------------------------------------


In [25]:
import torch
import numpy as np 
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [27]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [28]:
X_train , X_test , y_train , y_test = train_test_split(df.iloc[: , 1:] , df.iloc[: , 0] , test_size=0.2)

In [29]:
scaler = StandardScaler()
encoder = LabelEncoder()

In [30]:
X_train_transform = scaler.fit_transform(X_train)
X_test_transform = scaler.transform(X_test)

In [31]:
y_train_transform = encoder.fit_transform(y_train)
y_test_transform = encoder.transform(y_test)

In [32]:
X_train_tensor = torch.from_numpy(X_train_transform).float()
y_train_tensor = torch.from_numpy(y_train_transform).float()

X_test_tensor  = torch.from_numpy(X_test_transform).float()
y_test_tensor  = torch.from_numpy(y_test_transform).float()

In [33]:
from torch.utils.data import Dataset , DataLoader

In [34]:
class CustomDataset(Dataset):
    def __init__(self , features , labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self , index):
        return self.features[index] , self.labels[index]

In [47]:
train_dataset = CustomDataset(X_train_tensor , y_train_tensor)
test_dataset = CustomDataset(X_test_tensor ,  y_test_tensor )

In [48]:
train_dataset[10]

(tensor([ 0.2164, -0.4127,  0.1850,  0.0488,  1.4245,  0.4839,  0.7813,  0.9227,
          0.4876, -0.0881,  3.0591,  0.4456,  2.6308,  1.2585,  1.0855,  0.5345,
          1.0834,  2.6478,  3.6415, -0.3268,  0.4496, -0.6889,  0.3996,  0.1386,
          0.4004, -0.2358,  0.2832,  0.7633,  0.8156, -0.6800]),
 tensor(1.))

In [49]:
train_loader = DataLoader(train_dataset , batch_size = 32 , shuffle = True)
test_loader = DataLoader(test_dataset , batch_size = 32 , shuffle = True)

In [50]:
import torch.nn as nn

In [55]:
class MySimpleNN(nn.Module):
    def __init__(self , num_features):
        super().__init__()
        self.linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self ,features) :
        out = self.linear(features)
        out = self.sigmoid(out)

        return out 


In [56]:
learning_rate = 0.1 
epochs = 25

In [57]:
model = MySimpleNN(X_train_tensor.shape[1])
# create optimizer
optimizer = torch.optim.SGD(model.parameters() , lr = learning_rate )
# create loss function
loss_function = nn.BCELoss()

In [58]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.3045165240764618
Epoch: 2, Loss: 0.36838850378990173
Epoch: 3, Loss: 0.11407072097063065
Epoch: 4, Loss: 0.18314865231513977
Epoch: 5, Loss: 0.06602219492197037
Epoch: 6, Loss: 0.12755627930164337
Epoch: 7, Loss: 0.1442141830921173
Epoch: 8, Loss: 0.06596969068050385
Epoch: 9, Loss: 0.11345084756612778
Epoch: 10, Loss: 0.06397880613803864
Epoch: 11, Loss: 0.010294191539287567
Epoch: 12, Loss: 0.09140224009752274
Epoch: 13, Loss: 0.019903164356946945
Epoch: 14, Loss: 0.05578133836388588
Epoch: 15, Loss: 0.11241824924945831
Epoch: 16, Loss: 0.04703431949019432
Epoch: 17, Loss: 0.07088685035705566
Epoch: 18, Loss: 0.10009580105543137
Epoch: 19, Loss: 0.02920888550579548
Epoch: 20, Loss: 0.02642849087715149
Epoch: 21, Loss: 0.03590964898467064
Epoch: 22, Loss: 0.04388869181275368
Epoch: 23, Loss: 0.15229500830173492
Epoch: 24, Loss: 0.049981530755758286
Epoch: 25, Loss: 0.052773598581552505


In [59]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9210
