In [22]:
import torch
import torch.nn as nn

In [23]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.Linear = nn.Linear(num_features , 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self , features):
        out = self.Linear(features)
        out = self.sigmoid(out)

        return out


In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features) # inbuilt __call__ which calls forward function 


tensor([[0.3442],
        [0.4061],
        [0.4007],
        [0.4403],
        [0.4538],
        [0.4304],
        [0.4259],
        [0.4560],
        [0.4766],
        [0.4019]], grad_fn=<SigmoidBackward0>)

In [27]:
model.Linear.bias

Parameter containing:
tensor([-0.2989], requires_grad=True)

In [28]:
model.Linear.weight

Parameter containing:
tensor([[ 0.3279,  0.3835, -0.3369, -0.3526, -0.0021]], requires_grad=True)

In [29]:
!pip install torchinfo

In [30]:
from torchinfo import summary

In [31]:
summary(model , input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# creating again with 3 neurons in hidden layer 



In [37]:
class Model(nn.Module):
    def __init__(self , num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features , 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3 , 1 )
        self.sigmoid = nn.Sigmoid()

    def forward(self , features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)

        return out 


In [39]:
features = torch.rand(10,5)

model = Model(features.shape[1])

model(features) # __call__ is inbuilt which directly calls forward

tensor([[0.3917],
        [0.4207],
        [0.3929],
        [0.4636],
        [0.3586],
        [0.3729],
        [0.4500],
        [0.3950],
        [0.3647],
        [0.4308]], grad_fn=<SigmoidBackward0>)

In [41]:
model.linear1.weight

Parameter containing:
tensor([[-0.4407,  0.3845,  0.2801, -0.0249, -0.0814],
        [-0.3358,  0.2298, -0.3099,  0.1798,  0.2399],
        [ 0.2807, -0.2478, -0.0757, -0.4439, -0.0963]], requires_grad=True)

In [42]:
model.linear2.weight

Parameter containing:
tensor([[-0.4503, -0.5372,  0.4823]], requires_grad=True)

In [43]:
model.linear1.bias

Parameter containing:
tensor([0.2166, 0.3794, 0.0879], requires_grad=True)

In [44]:
summary(model , input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# using sequential containers


In [45]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [46]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6606],
        [0.6401],
        [0.6483],
        [0.6460],
        [0.6808],
        [0.6605],
        [0.6373],
        [0.6563],
        [0.6508],
        [0.6511]], grad_fn=<SigmoidBackward0>)