In [1]:
import torch



In [ ]:
# print version of python
print(torch.__version__)  

2.9.0+cpu


In [ ]:
# checking if GPU is available
if torch.cuda.is_available():
    print('GPU is available')
    print(f' using GPU : {torch.cuda.get_device_name}')
else :
    print('Using CPU')

Using CPU


## Creating a Tensor

In [116]:
# creating a 2,3 dimension of empty tensor 
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.2119, 0.0588, 0.4775],
        [0.3827, 0.4645, 0.2846]])

In [9]:
torch.manual_seed(99)  ## the value which is inside is unique everytime we call func with this value we will get same tensor

In [10]:
torch.rand(2,3)

tensor([[0.1033, 0.9702, 0.9481],
        [0.9787, 0.3268, 0.9200]])

In [11]:
torch.manual_seed(99)

In [12]:
torch.rand(2,3)


tensor([[0.1033, 0.9702, 0.9481],
        [0.9787, 0.3268, 0.9200]])

In [13]:
# using tensor
torch.tensor([[1,2,3] , [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [15]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [117]:
# creates identity tensor 
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:

torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [18]:
x = torch.tensor([[1,2,3,] , [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[          384616976,           377941856,   72340172838076673],
        [4687746815133016833,                  80,                  96]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x , dtype =torch.float64)

tensor([[0.4022, 0.8863, 0.3845],
        [0.5309, 0.6328, 0.8049]], dtype=torch.float64)

In [24]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

## tensor data types

In [25]:
x.dtype

torch.int64

In [26]:
torch.tensor([1.0,2.0,3.0] , dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1,2,3] , dtype=torch.float32)

tensor([1., 2., 3.])

In [28]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [29]:
x = torch.rand(2,2)

In [30]:
x

tensor([[0.7474, 0.5498],
        [0.0670, 0.1168]])

In [31]:
x+2

tensor([[2.7474, 2.5498],
        [2.0670, 2.1168]])

In [32]:
x-2

tensor([[-1.2526, -1.4502],
        [-1.9330, -1.8832]])

In [33]:
x*3

tensor([[2.2422, 1.6494],
        [0.2010, 0.3503]])

In [34]:
x/3

tensor([[0.2491, 0.1833],
        [0.0223, 0.0389]])

In [35]:
(x*100)//3

tensor([[24., 18.],
        [ 2.,  3.]])

In [36]:
((x*100)//3)%2

tensor([[0., 0.],
        [0., 1.]])

In [37]:
x**2

tensor([[0.5586, 0.3023],
        [0.0045, 0.0136]])

# Element wise Operation

In [38]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [39]:
a

tensor([[0.1724, 0.9940, 0.6244],
        [0.3656, 0.5017, 0.2137]])

In [40]:
b

tensor([[0.8108, 0.7784, 0.2362],
        [0.2899, 0.3328, 0.9092]])

In [41]:
a+b

tensor([[0.9832, 1.7724, 0.8606],
        [0.6555, 0.8346, 1.1229]])

In [42]:
a-b

tensor([[-0.6384,  0.2156,  0.3881],
        [ 0.0758,  0.1689, -0.6955]])

In [43]:
a*b

tensor([[0.1398, 0.7737, 0.1475],
        [0.1060, 0.1670, 0.1943]])

In [44]:
a/b

tensor([[0.2126, 1.2770, 2.6430],
        [1.2613, 1.5076, 0.2350]])

In [45]:
a//b

tensor([[0., 1., 2.],
        [1., 1., 0.]])

In [46]:
a%b

tensor([[0.1724, 0.2156, 0.1519],
        [0.0758, 0.1689, 0.2137]])

In [47]:
c = torch.tensor([1,2,-3,-5,7])

In [48]:
torch.abs(c)

tensor([1, 2, 3, 5, 7])

In [49]:
torch.neg(c)

tensor([-1, -2,  3,  5, -7])

In [50]:
d = torch.tensor([1 , -3 , 2.9 , 2.5 , 0.01 , 5])

In [51]:
torch.round(d)

tensor([ 1., -3.,  3.,  2.,  0.,  5.])

In [52]:
torch.ceil(d)

tensor([ 1., -3.,  3.,  3.,  1.,  5.])

In [53]:
torch.floor(d)

tensor([ 1., -3.,  2.,  2.,  0.,  5.])

In [54]:
torch.clamp(d , min=2 , max=3) # clamp 

tensor([2.0000, 2.0000, 2.9000, 2.5000, 2.0000, 3.0000])

In [55]:
e = torch.randint(size=(2,3) , low=0 , high=10 , dtype=torch.float32)

In [56]:
e

tensor([[8., 9., 9.],
        [0., 9., 8.]])

In [57]:
torch.sum(e)



tensor(43.)

In [58]:
# colwise
torch.sum(e , dim=0)


tensor([ 8., 18., 17.])

In [59]:
# rowise
torch.sum(e , dim=1)

tensor([26., 17.])

In [60]:
torch.mean(e)

tensor(7.1667)

In [61]:
torch.mean(e , dim=0) #colwise

tensor([4.0000, 9.0000, 8.5000])

In [62]:
torch.mean(e , dim=1) #rowise

tensor([8.6667, 5.6667])

In [63]:
torch.median(e)

tensor(8.)

In [64]:
torch.max(e)

tensor(9.)

In [65]:
torch.min(e , dim=0 )

torch.return_types.min(
values=tensor([0., 9., 8.]),
indices=tensor([1, 0, 1]))

In [66]:
torch.min(e , dim=1)

torch.return_types.min(
values=tensor([8., 0.]),
indices=tensor([0, 0]))

In [67]:
e

tensor([[8., 9., 9.],
        [0., 9., 8.]])

In [68]:
# argmax
torch.argmax(e)  #returns the index of max value

tensor(1)

In [69]:
torch.argmin(e) #return the index of min value

tensor(3)

In [70]:
f = torch.randint(size=(2,3) , low=0 , high=10)
g = torch.randint(size=(3,3) , low=0 , high=10)

In [71]:
torch.matmul(f,g)

tensor([[ 88,  34,  26],
        [141,  73,  55]])

In [72]:
vector1 = torch.tensor([2,3,4])
vector2 = torch.tensor([1,2,9])

In [73]:
torch.dot(vector1 , vector2)

tensor(44)

In [74]:
torch.transpose(f,1,0)

tensor([[2, 4],
        [4, 9],
        [7, 9]])

In [75]:
f

tensor([[2, 4, 7],
        [4, 9, 9]])

In [76]:
h = torch.randint(size=(3,3) , low =0 , high=10 , dtype=torch.float32)

In [77]:
h

tensor([[9., 3., 0.],
        [0., 8., 9.],
        [5., 7., 2.]])

In [78]:
torch.det(h)

tensor(-288.0000)

In [79]:
torch.inverse(h)

tensor([[ 0.1632,  0.0208, -0.0938],
        [-0.1563, -0.0625,  0.2813],
        [ 0.1389,  0.1667, -0.2500]])

## comparison operators

In [80]:
i = torch.randint(size=(2,3) , low=0 , high=10 , dtype=torch.float32)
j = torch.randint(size=(2,3) , low=0 , high=10 , dtype=torch.float32)

In [81]:
i>j

tensor([[False, False,  True],
        [ True,  True,  True]])

In [82]:
i==j

tensor([[False, False, False],
        [False, False, False]])

In [83]:
i<j

tensor([[ True,  True, False],
        [False, False, False]])

In [84]:
k = torch.randint(size=(2,3) , low=10 , high=20  , dtype = torch.float32)

In [85]:
k


tensor([[17., 16., 16.],
        [11., 16., 11.]])

In [86]:
torch.log(k)

tensor([[2.8332, 2.7726, 2.7726],
        [2.3979, 2.7726, 2.3979]])

In [87]:
torch.exp(k)

tensor([[24154952.0000,  8886111.0000,  8886111.0000],
        [   59874.1406,  8886111.0000,    59874.1406]])

In [88]:
torch.sigmoid(k)

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])

In [89]:
torch.softmax(k , dim=0)

tensor([[0.9975, 0.5000, 0.9933],
        [0.0025, 0.5000, 0.0067]])

In [90]:
torch.relu(k )

tensor([[17., 16., 16.],
        [11., 16., 11.]])

## inplace operations

In [91]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [92]:
m


tensor([[0.6902, 0.9020, 0.3685],
        [0.5174, 0.8765, 0.2990]])

In [93]:
n

tensor([[0.9685, 0.0940, 0.7392],
        [0.6004, 0.6739, 0.3602]])

In [94]:
m.add_(n)

tensor([[1.6587, 0.9960, 1.1077],
        [1.1177, 1.5503, 0.6593]])

In [95]:
m

tensor([[1.6587, 0.9960, 1.1077],
        [1.1177, 1.5503, 0.6593]])

In [96]:
torch.relu(m)

tensor([[1.6587, 0.9960, 1.1077],
        [1.1177, 1.5503, 0.6593]])

In [97]:
m.relu_()

tensor([[1.6587, 0.9960, 1.1077],
        [1.1177, 1.5503, 0.6593]])

In [98]:
m

tensor([[1.6587, 0.9960, 1.1077],
        [1.1177, 1.5503, 0.6593]])

In [99]:
a = torch.rand(2,3)

In [100]:
a

tensor([[0.8780, 0.6231, 0.3570],
        [0.8145, 0.6073, 0.5125]])

In [101]:
b=a

In [102]:
b

tensor([[0.8780, 0.6231, 0.3570],
        [0.8145, 0.6073, 0.5125]])

In [103]:
type(a)

torch.Tensor

In [104]:
id(a)

134307610262608

In [105]:

id(b)

134307610262608

In [106]:
a[0][0]=10

In [107]:
b

tensor([[10.0000,  0.6231,  0.3570],
        [ 0.8145,  0.6073,  0.5125]])

In [108]:
b = a.clone()

In [109]:
b

tensor([[10.0000,  0.6231,  0.3570],
        [ 0.8145,  0.6073,  0.5125]])

In [110]:
a[0][0]=5

In [111]:
b

tensor([[10.0000,  0.6231,  0.3570],
        [ 0.8145,  0.6073,  0.5125]])

In [112]:
id(b)

134307610210256

In [113]:
id(a)

134307610262608

In [114]:
torch.cuda.is_available()

False

In [115]:
a

tensor([[5.0000, 0.6231, 0.3570],
        [0.8145, 0.6073, 0.5125]])

In [118]:
b = torch.rand(2,3)

In [119]:
b

tensor([[0.6409, 0.1860, 0.5974],
        [0.1584, 0.1545, 0.8474]])

In [122]:
# permute
b.permute(1,0)
# first index ele comes on second index 
# second index ele comes on first index

tensor([[0.6409, 0.1584],
        [0.1860, 0.1545],
        [0.5974, 0.8474]])

In [123]:
# unsqueeze
#  adds a new dimension on a given index
a = torch.rand(226,226,3)


In [124]:
a

tensor([[[0.3584, 0.6629, 0.4294],
         [0.4718, 0.3984, 0.7621],
         [0.7941, 0.6271, 0.3249],
         ...,
         [0.6657, 0.8527, 0.2001],
         [0.2415, 0.5651, 0.6889],
         [0.5839, 0.0820, 0.7542]],

        [[0.2975, 0.1863, 0.6484],
         [0.0506, 0.9001, 0.7307],
         [0.1295, 0.2832, 0.0343],
         ...,
         [0.5250, 0.3631, 0.1212],
         [0.9574, 0.8370, 0.5417],
         [0.8192, 0.9045, 0.4945]],

        [[0.3593, 0.7530, 0.3653],
         [0.6683, 0.7231, 0.0881],
         [0.1984, 0.0783, 0.9755],
         ...,
         [0.3487, 0.3465, 0.2923],
         [0.8278, 0.8910, 0.4851],
         [0.9478, 0.7279, 0.0238]],

        ...,

        [[0.3609, 0.4636, 0.4804],
         [0.2409, 0.0690, 0.3379],
         [0.8260, 0.0783, 0.0174],
         ...,
         [0.0854, 0.9021, 0.9907],
         [0.9902, 0.0974, 0.5358],
         [0.4313, 0.6501, 0.0509]],

        [[0.3611, 0.7781, 0.7599],
         [0.4548, 0.2685, 0.5278],
         [0.

In [128]:
a.unsqueeze(0).shape
# a new dimension is added at zero index

torch.Size([1, 226, 226, 3])

In [168]:
# squeeze
d = torch.rand( 1,10,1,1,1,5)
d.shape


torch.Size([1, 10, 1, 1, 1, 5])

In [173]:
# squeeze removes on dimension=1
d.squeeze().shape

torch.Size([10, 5])

In [174]:
# converting numpy to tensor 


In [175]:
import numpy as np

In [179]:
a = torch.tensor([1,2,3,4])

In [180]:
b = a.numpy()

In [181]:
type(b)

numpy.ndarray

In [182]:
type(a)

torch.Tensor

In [187]:
c = np.array([1,2,3,4])

In [189]:
type(c)

numpy.ndarray

In [191]:
x = torch.from_numpy(c)

In [192]:
x

tensor([1, 2, 3, 4])

In [194]:
type(x)

torch.Tensor